### ISSUE TITLE
MOCKUPS: Search vs. View Patients

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening-ui-prototypes#18]
Talking with @esmithayer and @bengolder yesterday we agreed it would be useful to see what the use of listing patients beneath the search space is. Since we are looking at expanding search (#15) that includes showing patients _in_ and _out_ of network, what does the list beneath search include?

Here were some options/thoughts:
1. Is there an option to have the landing page ONLY show search, and then have a "view patients" page as a separate view?
2. Opposite of above: could we remove the "view your patients" section and just have that functionality (filtering) exist entirely beneath the search portion?
   1. what filter options exist?
   2. what is the default view of patients?

I'm going to work on mockups of 1 and 2 above!

**Comment by mapsam** [comment]
For number 1 - we could think about completely centering (vertically and horizontally) the search field to make absolutely sure that search is the main objective (recognizing that search isn't necessarily the main objective).

![screen shot 2015-07-15 at 1 43 48 pm](https://cloud.githubusercontent.com/assets/1943001/8709531/b0651882-2af7-11e5-8b6d-657504c80e1b.png)

**Comment by mapsam** [comment]
Here's a start on the second thought, of having a unique page to view patients. As I work on this page more, it is kind of turning into a dashboard page, which could potentially become an admin page for looking at major statistics:

<img width="1184" alt="screen shot 2015-07-15 at 6 17 12 pm" src="https://cloud.githubusercontent.com/assets/1943001/8713482/e93f0f8e-2b1d-11e5-968d-e56df9a26c09.png">

**Comment by mapsam** [comment]
As I go through making up statistics, it actually seems like an interesting way to filter on the page:

<img width="836" alt="screen shot 2015-07-15 at 6 44 03 pm" src="https://cloud.githubusercontent.com/assets/1943001/8713765/9a98077e-2b21-11e5-8c1a-06a29f00d447.png">

What if you could click those stats to view the specific patients?

<img width="1136" alt="screen shot 2015-07-15 at 7 29 52 pm" src="https://cloud.githubusercontent.com/assets/1943001/8714280/e62b13c4-2b27-11e5-9204-a3c0eda97404.png">

**Comment by mapsam** [comment]
And of course, the combination view:

<img width="906" alt="screen shot 2015-07-15 at 7 26 54 pm" src="https://cloud.githubusercontent.com/assets/1943001/8714231/890c67d8-2b27-11e5-8df4-b29006367f47.png">

**Comment by esmithayer** [comment]
I think I like the combined page better, and I like the stats on the left that filter the list. A couple thoughts on those categories:
- What does "new patients" mean? Patients this user added recently? Patients this organization added recently? Patients added anywhere in the network recently? Same for "updated today."
- "haven't been updated in over a year" seems like it would have lots of patients who end up there forever, so not sure how useful it is to have that count on a dashboard. It might be useful to use those colored indicators next to a patient's name to mark patients with out-of-date information, though (it sounded like the Fairfax app does something like that).
- Not sure what the concepts of "your organization's patients" and "your patients who were screened elsewhere" mean if there's umbrella sharing.
- Other things that might be useful: patients who have applied or been referred to my organization but haven't received a screening decision yet, patients we recently referred elsewhere.

**Comment by mapsam** [comment]
Cool. I agree about the combo page!

In regards to the statistic navigation buttons - those are totally in there as an example. I would love to figure out a few to start with and get feedback on what other numbers people would want to see when we travel next.

Decision to move forward with combo page? :+1: from me.

**Comment by bengolder** [comment]
:+1: to combo page, with filters on left.

Deciding which filters & categories should exist seems like a separate decision, but one that we should test our assumptions on during this visit. Can we make a separate issue for that where we can throw out ideas?

**Comment by mapsam** [comment]
Totally.

### Decision is to go with a combo search/view patients page. Onward!
