### ISSUE TITLE
MOCKUP: patient history and "where they have been"

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening-ui-prototypes#24]
When looking at a patient's edit history, how do we visualize each edit and important events?

**Comment by bengolder** [comment]
**An administrator** may be looking at the history to do an audit or to evaluate staff performance. They will probably want information on the referral history of a patient population for a given time period.

Right now, such information is probably best available as a CSV dump of:
1. the history of actions of a staff member, for a given time period
2. the history of edits to a patient's info by anyone, for a given time period
3. referrals made and accepted by a particular staff member, for a given time period.

**A navigator** would want to know _past values of certain fields_, particularly contact information (this was mentioned explicitly by at least 3 different navigators). They would also want to know where else a patient has been seen, for the purpose of making better referrals, or being able to get more details about the patient's history.

**A screener** would likely want to know where else the patient had been seen, particularly if that  information would help determine eligibility or (in the case of being ineligible) deflect the patient to a more appropriate place.
- an in-context link to previous values and who entered those values for each field seems valuable.
- Patient details should include a prominent list about where a patient has been

An in-context link example:
<img src="https://cloud.githubusercontent.com/assets/451510/8837371/e63844d8-307a-11e5-8667-29a7f90e7c87.png" width=500>

**Comment by mapsam** [comment]
Seems like separating "events" (visits/shares) from "edits" would be important. Let's focus on patient information first - and once we have user roles established we can work on views for user statistics.

**Comment by mapsam** [comment]
:+1: for in-context edit history. Going to do some mockups for in-context edit history in #27

:+1: for patient details view of visit/share history in #28
