### ISSUE TITLE
Font thoughts

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening-ui-prototypes#34]
We recently chose Arial and Verdana due to wide cross-platform support.

It occurred to me that instead of choosing the most widely-available font, we could choose several different great fonts that exist natively on the platforms we are designing for.

I assume the most common platforms used to access the app would be:
Windows 7
Android phones of various levels
rarely OS X

So far, most of the orgs I've seen are running Windows 7. We could use [Segoe UI](http://www.microsoft.com/typography/fonts/family.aspx?FID=331) for Windows 7 & 8.
For Android phones we could use [Roboto](https://www.google.com/fonts/specimen/Roboto)
For OS X, we could use Helvetica Neue or something else which allows us to get similar gradations of font weight to Roboto and Segoe UI. OS X will probably be the least used platform.

So the font stack might be designated as:

```
  font-family: "Segoe UI", "Roboto", "Helvetica Neue", sans-serif;
```

What do you think?

Segoe UI
![screen shot 2015-07-31 at 11 16 55 am](https://cloud.githubusercontent.com/assets/451510/9010581/b3084598-3775-11e5-9a33-a7f0458191d3.png)

Roboto
![screen shot 2015-07-31 at 11 17 43 am](https://cloud.githubusercontent.com/assets/451510/9010599/ced7d338-3775-11e5-8fd0-25fe8c82687a.png)

Helvetica Neue
![screen shot 2015-07-31 at 11 19 01 am](https://cloud.githubusercontent.com/assets/451510/9010623/fccdae52-3775-11e5-8e48-32ac34fb2255.png)

**Comment by mapsam** [comment]
I can dig it! I like Roboto a lot, and wish it worked across them all. Segoe looks great, though - excited to see a Windows with a relatively classy font family.

I'm not sold on Helvetica, but since it's the third fallback I'm not going to worry about it too heavily right now. Are these fonts proposals for headers, body, or both?

**Comment by bengolder** [comment]
I was thinking everything (body & header). And I agree, Helvetica is less than ideal. I just picked it due to it being native, sans-serif, and having a similar weight range. I looked at Lucida Grande, but that only seems to have bold and regular weights. If you notice any better ones for Mac we should try that.

We can install Roboto locally and use that for prototyping.

**Comment by mapsam** [comment]
I say we stick with it for now, esp. because the weight range is excellent.

Here is a Roboto webfont download source: https://code.google.com/p/roboto-webfont/downloads/list OR http://www.fontsquirrel.com/fonts/roboto

**Comment by bengolder** [comment]
:+1: awesome!

**Comment by mapsam** [comment]
Added new font stack to my machine and to the CSS variables. Yay!

``` CSS
font-family: "Segoe UI", "Roboto", "Helvetica Neue", sans-serif;
```
